/**
 * Reading-order check for multi-column PDFs.
 *
 * Generates two-, three-column and mixed-layout pages in Chrome (CSS columns,
 * a full-width title/abstract and a `column-span: all` caption in the middle),
 * prints them to PDF, converts them back and compares the order in which the
 * numbered sentences come out with the order they went in.
 *
 * Metric: pairwise order accuracy over all sentence pairs (1.0 = perfect
 * reading order, 0.5 = random) plus the count of adjacent inversions. The
 * same documents printed single-column are checked too, so the column logic
 * is proven not to disturb an ordinary page.
 *
 *   pnpm --filter @jdf/pdf-import verify:order            # needs Google Chrome (Playwright channel "chrome")
 *   pnpm --filter @jdf/pdf-import verify:order some.pdf   # print the element-order text of a real PDF's first pages
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { chromium } from "playwright";
import { importPdfToJdf } from "../src/node";

const words = "retrieval pipeline column layout token budget chunk boundary heading table figure caption index vector recall latency budget storage format schema render".split(" ");
function sentence(i: number, rnd: () => number): string {
  const n = 6 + Math.floor(rnd() * 8);
  const w: string[] = [];
  for (let k = 0; k < n; k++) w.push(words[Math.floor(rnd() * words.length)]);
  return `S${String(i).padStart(3, "0")} ${w.join(" ")}.`;
}
function rng(seed: number) { let s = seed; return () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; }; }

interface Layout { name: string; columns: number; sentences: number; spanCaption: boolean; }
const layouts: Layout[] = [
  { name: "single-column", columns: 1, sentences: 60, spanCaption: false },
  { name: "two-column", columns: 2, sentences: 90, spanCaption: false },
  { name: "two-column+span", columns: 2, sentences: 90, spanCaption: true },
  { name: "three-column", columns: 3, sentences: 100, spanCaption: false },
];

function html(l: Layout): { html: string; order: number[] } {
  const rnd = rng(42);
  const order: number[] = [];
  const paras: string[] = [];
  let i = 1;
  while (i <= l.sentences) {
    const per = 3 + Math.floor(rnd() * 3);
    const ss: string[] = [];
    for (let k = 0; k < per && i <= l.sentences; k++, i++) { ss.push(sentence(i, rnd)); order.push(i); }
    paras.push(`<p>${ss.join(" ")}</p>`);
  }
  const mid = Math.floor(paras.length / 2);
  if (l.spanCaption) paras.splice(mid, 0, `<div class="span"><b>Figure 1.</b> A full-width caption that interrupts both columns; text above it must be read before it, text below after it.</div>`);
  // Make the body of the column section reasonably long so it fills a page.
  return {
    order,
    html: `<!doctype html><html><head><meta charset="utf-8"><style>
      @page { size: A4; margin: 18mm 16mm; }
      body { font-family: Helvetica, Arial, sans-serif; font-size: 10pt; line-height: 1.35; margin: 0; color: #111; }
      h1 { font-size: 20pt; margin: 0 0 6pt; }
      .abstract { font-size: 9.5pt; margin: 0 14mm 8mm; font-style: italic; }
      .cols { column-count: ${l.columns}; column-gap: 7mm; }
      p { margin: 0 0 5pt; text-align: justify; }
      .span { column-span: all; border-top: 0.5pt solid #999; border-bottom: 0.5pt solid #999; padding: 4pt 0; margin: 4pt 0 6pt; font-size: 9pt; }
    </style></head><body>
      <h1>Reading order fixture · ${l.name}</h1>
      <div class="abstract">This page is generated by verify-order.ts. Sentences carry a running number in reading order; the importer must reproduce that sequence across ${l.columns} column(s).</div>
      <div class="cols">${paras.join("\n")}</div>
    </body></html>`,
  };
}

function extractOrder(doc: any): number[] {
  const seen: number[] = [];
  const push = (t: string) => { for (const m of t.matchAll(/S(\d{3})/g)) seen.push(Number(m[1])); };
  const walk = (els: any[]) => {
    for (const e of els) {
      if (e.type === "text") push(String(e.content ?? ""));
      else if (e.type === "richtext") push((e.runs ?? []).map((r: any) => r.text ?? "").join(""));
      else if (e.type === "table") { for (const r of e.rows ?? []) for (const c of r) push(typeof c === "string" ? c : String(c?.content ?? "")); }
      if (Array.isArray(e.elements)) walk(e.elements);
    }
  };
  for (const p of doc.pages) walk(p.elements);
  return seen;
}

function pairwise(seq: number[]): { acc: number; inversions: number; adjacentBreaks: number } {
  let good = 0, total = 0, inv = 0;
  for (let i = 0; i < seq.length; i++) for (let j = i + 1; j < seq.length; j++) { total++; if (seq[i] < seq[j]) good++; else inv++; }
  let breaks = 0;
  for (let i = 1; i < seq.length; i++) if (seq[i] !== seq[i - 1] + 1) breaks++;
  return { acc: total ? good / total : 1, inversions: inv, adjacentBreaks: breaks };
}

async function main() {
  const real = process.argv[2];
  if (real) {
    const doc = await importPdfToJdf(real, path.basename(real), {});
    for (const [pi, p] of doc.pages.slice(0, 2).entries()) {
      console.log(`\n═══ page ${pi + 1} — element order ═══`);
      for (const e of p.elements as any[]) {
        const t = e.type === "text" ? e.content : e.type === "richtext" ? e.runs.map((r: any) => r.text).join("") : e.type === "table" ? `[table ${e.rows.length}×${(e.headers ?? e.rows[0] ?? []).length}]` : null;
        if (t) console.log(`  ${String(e.position.x).padStart(6)} ${String(e.position.y).padStart(6)}  ${String(t).slice(0, 90)}`);
      }
    }
    return;
  }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "jdf-order-"));
  const browser = await chromium.launch({ channel: "chrome", headless: true });
  const page = await browser.newPage();
  let failed = false;
  for (const l of layouts) {
    const { html: h, order } = html(l);
    const f = path.join(tmp, `${l.name}.html`);
    fs.writeFileSync(f, h);
    await page.goto(`file://${f}`);
    const pdf = path.join(tmp, `${l.name}.pdf`);
    await page.pdf({ path: pdf, format: "A4", printBackground: true, preferCSSPageSize: true });
    for (const readingOrder of [false, true]) {
      const doc = await importPdfToJdf(pdf, l.name, { readingOrder });
      const seq = extractOrder(doc);
      const m = pairwise(seq);
      const missing = order.filter((n) => !seq.includes(n)).length;
      const tables = doc.pages.reduce((a: number, p: any) => a + p.elements.filter((e: any) => e.type === "table").length, 0);
      const pass = readingOrder ? m.acc >= 0.995 && missing === 0 && tables === 0 : true;
      if (!pass) failed = true;
      console.log(`${readingOrder ? (pass ? "✓" : "✗") : "·"} ${l.name.padEnd(18)} readingOrder=${String(readingOrder).padEnd(5)} pairwise ${(m.acc * 100).toFixed(1)}%  inversions ${String(m.inversions).padStart(5)}  adjacent breaks ${String(m.adjacentBreaks).padStart(3)}  sentences ${seq.length}/${order.length}${missing ? `  MISSING ${missing}` : ""}${tables ? `  FALSE TABLES ${tables}` : ""}`);
    }
  }
  await browser.close();
  console.log(`\nfixtures in ${tmp}`);
  process.exit(failed ? 1 : 0);
}
main();
